name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web and macOS.
version: 7.0.1
homepage: https://github.com/darwin-morocho/flutter-facebook-auth
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_facebook_auth_platform_interface:
    git: https://github.com/halloglobal/facebook_auth_platform_interface.git
    
  # flutter_facebook_auth_web: ^6.0.0
  # flutter_facebook_auth_web:
  #   path: ../facebook_auth_web

  # facebook_auth_desktop: ^2.0.0
  # facebook_auth_desktop:
  #   path: ../facebook_auth_desktop
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
      macos:
        default_package: facebook_auth_desktop


